# Generated by Django 5.0.4 on 2024-05-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
